---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: objects.hnc.x-k8s.io
  timeoutSeconds: 2
  sideEffects: None
- name: subnamespaceanchors.hnc.x-k8s.io
  sideEffects: None
- name: hierarchyconfigurations.hnc.x-k8s.io
  sideEffects: None
- name: hncconfigurations.hnc.x-k8s.io
  sideEffects: None
- name: namespaces.hnc.x-k8s.io
  sideEffects: None
